authors:
  team:
    name: EE-Wiki Team
    description: 或许是站点核心维护团队
    avatar: https://avatars.githubusercontent.com/u/96403216?s=200&v=4
  tenktau:
    name: Wantao Liu
    description: 404 Not Found…
    avatar: https://avatars.githubusercontent.com/u/61775365?s=70&v=4